#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

if [[ "$new_path" != "/" ]]; then
    ynh_die --message="ChaptarrNG must remain at the root of a dedicated domain."
fi

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating ChaptarrNG's Nginx domain configuration..."
ynh_change_url_nginx_config

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Change of URL completed for $app"
